#!/bin/bash

while [ "a" = "a" ]
do
  curl https://oval-humane-pigment.glitch.me/
  curl https://aerial-quasar-study.glitch.me/
  sleep 7m
  wget https://oval-humane-pigment.glitch.me/
  wget https://aerial-quasar-study.glitch.me/
  sleep 6m
done
